### ISSUE TITLE
Float conversion error

### ISSUE THREAD

**Issue by arist0v** [WTIOAddons/date-time-adapter#10]
When i enter my lat and long, using coma as usual, i got a Float conversion error.

I created a fix in PR #9  to convert coma to dot and change it also in the db.

**Comment by wfahle** [comment]
I had to revise your commit to make it pass lint, but it is incorporated now. Give it a try.

**Comment by arist0v** [comment]
thank you,i must admit i was in kind of a busy day when i did this fix, and didn'T have time to test everything ;-) i make sure the logic was ok, but did run test and all, hoping for the best ;-) happy it work and glad to help!
