### ISSUE TITLE
Required Python version not supported by WebThings Gateway 1.0

### ISSUE THREAD

**Issue by benfrancis** [WTIOAddons/date-time-adapter#12]
In https://discourse.mozilla.org/t/newbie-question-about-missing-addons/107097/5 it was reported that users of the WebThings Gateway 1.0 Raspberry Pi OS image are not seeing the date time adapter as available to install.

This appears to be because in the 1.1.6 release of the adapter, support was dropped for Python 3.7.

Unfortunately Python 3.7 is the latest version available in Raspbian/Debian Buster, upon which the WebThings Gateway 1.0 image is built (and likely some future releases will be built too).

When a gateway fetches the list of available add-ons it specifies the installed Python version in its request. If the add-on requires a newer version than the one installed then it isn't displayed.

Is there a functional reason why Python 3.8 is required, or could Python 3.7 support return?

**Comment by wfahle** [comment]
I couldn't get it to build a 3.7 image for the required targets using
github. I think we may need to roll back to the prior release of
datetimeadapter.

**Comment by wfahle** [comment]
I got this to build and there is a pending merge request for addons to push it to the current build. There are lots of pending deprecations of build actions, so any future updates will require quite a bit more pain. But this one is done; closing out.

**Comment by flatsiedatsie** [comment]
No need for pain, just copy my workflow:
https://github.com/createcandle/matter-adapter/blob/main/.github/workflows/release.yml

**Comment by wfahle** [comment]
> 

Hmm, it looks like you've left out v3.7 in your workflow. If you look at mine you will see that I changed the build for 3.7 to not rebuild everything from scratch, and just to use existing wheels and whatnot. It all works fine now.

**Comment by flatsiedatsie** [comment]
Ah, here:
https://github.com/WTIOAddons/date-time-adapter/blob/ed13e5a684d2bd8eed950a0f22515fcc707cc317/package.sh#L23

I was curious about that. @benfrancis Why does it normally build everything from scratch? Is that for security reasons?

**Comment by wfahle** [comment]
That was the way the sample I copied did it. No idea why.
