### ISSUE TITLE
Sunset/Sunrise and Dark seem to be backwards

### ISSUE THREAD

**Issue by chasingmaxwell** [WTIOAddons/date-time-adapter#6]
The "Sunset" event happens for me in the morning and the "Sunrise" event happens in the evening. Additionally, "Dark" is true all throughout the day. I've double checked my configuration and all seems to be correct.

![image](https://user-images.githubusercontent.com/3128659/113873342-bac5cd00-9782-11eb-86b0-96401732dc1b.png)

![image](https://user-images.githubusercontent.com/3128659/113873502-dfba4000-9782-11eb-83fd-fdfd691c897b.png)

![image](https://user-images.githubusercontent.com/3128659/113873640-fd87a500-9782-11eb-889f-be934d9caa7f.png)

Any ideas?

**Comment by wfahle** [comment]
Given your time zone, I would say that your longitude is entered backwards. It should be negative in this part of the world, so in your case -85.7585. Negative numbers in longitude indicated degrees west of the prime meridian, and negative numbers in lattitude indicate degrees south of the equator.

**Comment by chasingmaxwell** [comment]
You are 100% correct. I knew it was going to be something really silly like that. Thank you!
