### ISSUE TITLE
DateTime Not Weekend rule not seeming to function

### ISSUE THREAD

**Issue by nbackous** [WTIOAddons/date-time-adapter#8]
I have a simple rule that controls my home-office  light.

If DateTime = Not Weekend
AND
Time Of Day = 8:30AM
THEN
turn Office Overhead light ON

![Screen Shot 2021-08-08 at 11 26 09 AM](https://user-images.githubusercontent.com/40135245/128641980-4fbe7c67-7ef7-436d-a804-0e4dd7dd02d5.png)

But the light continues to turn on on Saturday and Sunday.

The DateTime Thing does report that today (Sunday) = Weekend

![Screen Shot 2021-08-08 at 11 29 51 AM](https://user-images.githubusercontent.com/40135245/128642088-9d64d889-d625-496b-9931-8e1b70a98eb7.png)

**Comment by wfahle** [comment]
Hi nbackous, thanks for the report. I have verified that a similar rule does turn on a light for me on the weekday, I will wait for the weekend to try to reproduce and see what the logs say, etc.

**Comment by wfahle** [comment]
Hi @nbackous I tried this out this weekend and it worked properly with a similar rule. Can you turn on logging and post a part of the log (under debugging) that fails, or otherwise offer steps to reproduce with the latest datetimeadaper? I will close otherwise. Thanks.

**Comment by wfahle** [comment]
Note that there is a known issue where if something has already happened the trigger may not occur until the next weekend, for example.

**Comment by nbackous** [comment]
I've since completely reconfigured my entire webthings environment and I can no longer reproduce this issue. The problem must've been on my side.
